.PHONY: clean All

All:
	@echo "----------Building project:[ Program - Debug ]----------"
	@cd "Program" && "$(MAKE)" -f  "Program.mk"
clean:
	@echo "----------Cleaning project:[ Program - Debug ]----------"
	@cd "Program" && "$(MAKE)" -f  "Program.mk" clean
